export interface DemoBranchConfig {
  enabled: boolean;
  submissionNumber: number | null;
  companyName: string | null;
  contactName: string | null;
  branchName: string | null;
  generatedAt: string | null;
  branding: DemoBranchBrandingConfig | null;
  navigationPriorityHrefs: string[];
  pdf: DemoBranchPdfConfig | null;
  welcome: DemoBranchWelcomeConfig | null;
}

export interface DemoBranchBrandingConfig {
  appName: string;
  shortAppName: string;
  companyName: string;
  brandColor: string;
  brandColorHover: string;
  brandColorLight: string;
  backgroundColor: string;
  logoPath: string;
  faviconPath: string;
  sourceUrl: string | null;
}

export interface DemoBranchPdfConfig {
  registeredOffice: string;
  contactLine: string;
  registrationLine: string;
}

export interface DemoBranchWelcomeConfig {
  companyDisplayName: string;
  industryLabel: string | null;
  operatingRegion: string | null;
  companySizeLabel: string | null;
  primaryDemoObjectiveLabel: string | null;
  priorityModuleLabels: string[];
  painPointLabels: string[];
  teamLabels: string[];
  assetLabels: string[];
  documentOutputLabels: string[];
}

export const demoBranchConfig: DemoBranchConfig = {
  enabled: true,
  submissionNumber: 6,
  companyName: "Forest Farm Tree Services",
  contactName: "Joe Cane",
  branchName: "demo/forest-farm-tree-services-submission-6",
  generatedAt: "2026-07-08T18:42:43.942Z",
  branding: {
  "appName": "Forest Farm Tree Services Operations",
  "shortAppName": "Forest Farm Tree Servi",
  "companyName": "Forest Farm Tree Services",
  "brandColor": "#F1D64A",
  "brandColorHover": "#CFB840",
  "brandColorLight": "#FCF8DE",
  "backgroundColor": "#0F172A",
  "logoPath": "/demo-personalisation/submission-6/logo.png",
  "faviconPath": "/demo-personalisation/submission-6/favicon.svg",
  "sourceUrl": "https://www.forestfarmtreeservices.co.uk/wp-content/uploads/2017/05/cropped-forest-farm-letter-heads-ok-1-32x32.png"
},
  navigationPriorityHrefs: [
  "/projects",
  "/inventory",
  "/quotes",
  "/customers",
  "/reports",
  "/van-inspections",
  "/plant-inspections",
  "/hgv-inspections"
],
  pdf: {
  "registeredOffice": "Forest Farm Tree Services, East Midlands",
  "contactLine": "Telephone: 07860650405",
  "registrationLine": "Personalised demo output generated by Forest Farm Tree Services"
},
  welcome: {
  "companyDisplayName": "Forest Farm Tree Services",
  "industryLabel": "Facilities, maintenance, or service teams",
  "operatingRegion": "East Midlands",
  "companySizeLabel": "Under 25 people",
  "primaryDemoObjectiveLabel": "It will save office/admin time",
  "priorityModuleLabels": [
    "Projects, RAMS, and compliance documents",
    "Inventory, tools, and equipment",
    "Quotes and customer records",
    "Reports and management visibility",
    "Van, HGV, or plant daily checks"
  ],
  "painPointLabels": [
    "Other, explained in the notes"
  ],
  "teamLabels": [
    "Management",
    "Accounts",
    "Civils/site teams",
    "Workshop",
    "Subcontractors or external users",
    "Plant",
    "Office/admin"
  ],
  "assetLabels": [
    "Vans or light commercial vehicles",
    "Plant and heavy machinery",
    "Small tools and equipment"
  ],
  "documentOutputLabels": [
    "Inspection or defect PDFs",
    "RAMS or project documents",
    "Quote PDFs"
  ]
},
};
