export interface TemplateBrandingConfig {
  appName: string;
  shortAppName: string;
  companyName: string;
  registeredAddress: string;
  supportEmail: string;
  supportPhone: string;
  adminEmail: string;
  publicUrl: string;
  logoPath: string;
  faviconPath: string;
  brandColor: string;
  brandColorHover: string;
  brandColorLight: string;
  backgroundColor: string;
  registrationText: string;
}

export interface TemplatePublicConfig {
  branding: TemplateBrandingConfig;
}

function readPublicEnv(value: string | undefined, fallback: string): string {
  return value && value.trim().length > 0 ? value.trim() : fallback;
}

export const templateConfig: TemplatePublicConfig = {
  branding: {
    appName: readPublicEnv(
      process.env.NEXT_PUBLIC_APP_NAME,
      'Forest Farm Tree Services Operations'
    ),
    shortAppName: readPublicEnv(
      process.env.NEXT_PUBLIC_SHORT_APP_NAME,
      'Forest Farm'
    ),
    companyName: readPublicEnv(
      process.env.NEXT_PUBLIC_COMPANY_NAME,
      'Forest Farm Tree Services'
    ),
    registeredAddress: readPublicEnv(
      process.env.NEXT_PUBLIC_COMPANY_ADDRESS,
      'Forest Farm Tree Services, East Midlands'
    ),
    supportEmail: readPublicEnv(
      process.env.NEXT_PUBLIC_SUPPORT_EMAIL,
      'support@example.test'
    ),
    supportPhone: readPublicEnv(
      process.env.NEXT_PUBLIC_SUPPORT_PHONE,
      'Telephone: 07860650405'
    ),
    adminEmail: readPublicEnv(
      process.env.NEXT_PUBLIC_ADMIN_EMAIL,
      'admin@mpdee.co.uk'
    ),
    publicUrl: readPublicEnv(
      process.env.NEXT_PUBLIC_APP_URL,
      readPublicEnv(process.env.NEXT_PUBLIC_SITE_URL, 'http://localhost:4000')
    ),
    logoPath: readPublicEnv(
      process.env.NEXT_PUBLIC_LOGO_PATH,
      '/images/forest-farm/logo.svg'
    ),
    faviconPath: readPublicEnv(
      process.env.NEXT_PUBLIC_FAVICON_PATH,
      '/images/forest-farm/favicon.svg'
    ),
    brandColor: readPublicEnv(process.env.NEXT_PUBLIC_BRAND_COLOR, '#F1D64A'),
    brandColorHover: readPublicEnv(
      process.env.NEXT_PUBLIC_BRAND_COLOR_HOVER,
      '#CFB840'
    ),
    brandColorLight: readPublicEnv(
      process.env.NEXT_PUBLIC_BRAND_COLOR_LIGHT,
      '#FCF8DE'
    ),
    backgroundColor: readPublicEnv(
      process.env.NEXT_PUBLIC_PWA_BACKGROUND_COLOR,
      '#0F172A'
    ),
    registrationText: readPublicEnv(
      process.env.NEXT_PUBLIC_COMPANY_REGISTRATION,
      'Generated by Forest Farm Tree Services Operations'
    ),
  },
};

export function getTemplateConfig(): TemplatePublicConfig {
  return templateConfig;
}

interface RgbColour {
  r: number;
  g: number;
  b: number;
}

function hexToRgb(hexValue: string): RgbColour | null {
  const normalized = hexValue.trim().replace(/^#/u, '');
  if (!/^[\da-f]{6}$/iu.test(normalized)) {
    return null;
  }

  return {
    r: Number.parseInt(normalized.slice(0, 2), 16),
    g: Number.parseInt(normalized.slice(2, 4), 16),
    b: Number.parseInt(normalized.slice(4, 6), 16),
  };
}

function hexToHslTriplet(hexValue: string, fallback: string): string {
  const rgb = hexToRgb(hexValue);
  if (!rgb) {
    return fallback;
  }

  const r = rgb.r / 255;
  const g = rgb.g / 255;
  const b = rgb.b / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const lightness = (max + min) / 2;
  const delta = max - min;

  if (delta === 0) {
    return `0 0% ${Math.round(lightness * 100)}%`;
  }

  const saturation = delta / (1 - Math.abs(2 * lightness - 1));
  const hue =
    max === r
      ? 60 * (((g - b) / delta) % 6)
      : max === g
        ? 60 * ((b - r) / delta + 2)
        : 60 * ((r - g) / delta + 4);

  return `${Math.round((hue + 360) % 360)} ${Math.round(saturation * 100)}% ${Math.round(lightness * 100)}%`;
}

export function getTemplateBrandCssVariables(): Record<string, string> {
  const backgroundColor = hexToHslTriplet(templateConfig.branding.backgroundColor, '222 47% 11%');

  return {
    '--background': backgroundColor,
    '--card': backgroundColor,
    '--popover': backgroundColor,
    '--brand-yellow': hexToHslTriplet(templateConfig.branding.brandColor, '48 87% 69%'),
    '--brand-yellow-hover': hexToHslTriplet(templateConfig.branding.brandColorHover, '48 73% 56%'),
    '--brand-yellow-light': hexToHslTriplet(templateConfig.branding.brandColorLight, '48 100% 94%'),
    '--primary': hexToHslTriplet(templateConfig.branding.brandColor, '48 87% 69%'),
    '--ring': hexToHslTriplet(templateConfig.branding.brandColor, '48 87% 69%'),
  };
}
