BEGIN;

CREATE TABLE IF NOT EXISTS public.schedule_visit_backlog (
  visit_id UUID PRIMARY KEY REFERENCES public.schedule_visits(id) ON DELETE CASCADE,
  original_starts_at TIMESTAMPTZ NOT NULL,
  original_ends_at TIMESTAMPTZ NOT NULL,
  queued_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  queued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  version INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT schedule_visit_backlog_version_check CHECK (version > 0),
  CONSTRAINT schedule_visit_backlog_time_range_check CHECK (
    original_ends_at > original_starts_at
  )
);

CREATE INDEX IF NOT EXISTS schedule_visit_backlog_queued_at_idx
  ON public.schedule_visit_backlog (queued_at DESC);

CREATE TABLE IF NOT EXISTS public.schedule_visit_transition_requests (
  request_id UUID PRIMARY KEY,
  action TEXT NOT NULL,
  visit_id UUID NOT NULL REFERENCES public.schedule_visits(id) ON DELETE CASCADE,
  actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  input_hash TEXT NOT NULL,
  result JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT schedule_visit_transition_requests_action_check CHECK (
    action IN ('enqueue', 'schedule')
  )
);

CREATE INDEX IF NOT EXISTS schedule_visit_transition_requests_visit_idx
  ON public.schedule_visit_transition_requests (visit_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.schedule_visit_transition_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id UUID,
  job_id UUID,
  action TEXT NOT NULL,
  actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  assignment_count INTEGER NOT NULL DEFAULT 0,
  from_starts_at TIMESTAMPTZ,
  from_ends_at TIMESTAMPTZ,
  to_starts_at TIMESTAMPTZ,
  to_ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT schedule_visit_transition_events_action_check CHECK (
    action IN ('enqueue', 'schedule')
  ),
  CONSTRAINT schedule_visit_transition_events_assignment_count_check CHECK (
    assignment_count >= 0
  )
);

CREATE INDEX IF NOT EXISTS schedule_visit_transition_events_visit_idx
  ON public.schedule_visit_transition_events (visit_id, created_at DESC);

ALTER TABLE public.schedule_visit_backlog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_visit_transition_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_visit_transition_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.schedule_visit_backlog FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.schedule_visit_transition_requests FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.schedule_visit_transition_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.schedule_visit_backlog TO service_role;
GRANT ALL ON TABLE public.schedule_visit_transition_requests TO service_role;
GRANT ALL ON TABLE public.schedule_visit_transition_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.schedule_visit_transition_events_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.schedule_visit_backlog_fingerprint_v1(
  p_visit_id UUID
)
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT md5(
    concat_ws(
      '|',
      visit.id::TEXT,
      visit.updated_at::TEXT,
      job.updated_at::TEXT,
      job.status::TEXT,
      COALESCE(quote.updated_at::TEXT, ''),
      COALESCE(quote.status::TEXT, ''),
      COALESCE(quote.commercial_status::TEXT, ''),
      COALESCE(quote.is_latest_version::TEXT, ''),
      COALESCE(quote.accepted::TEXT, ''),
      COALESCE(quote.start_date::TEXT, ''),
      COALESCE(quote.estimated_duration_days::TEXT, ''),
      COALESCE(
        (
          SELECT string_agg(
            assignment.id::TEXT || ':' || assignment.updated_at::TEXT,
            ',' ORDER BY assignment.id
          )
          FROM public.schedule_employee_assignments AS assignment
          WHERE assignment.visit_id = visit.id
        ),
        ''
      ),
      COALESCE(
        (
          SELECT string_agg(
            assignment.id::TEXT || ':' || assignment.updated_at::TEXT,
            ',' ORDER BY assignment.id
          )
          FROM public.schedule_plant_assignments AS assignment
          WHERE assignment.visit_id = visit.id
        ),
        ''
      )
    )
  )
  FROM public.schedule_visits AS visit
  JOIN public.schedule_jobs AS job ON job.id = visit.job_id
  LEFT JOIN public.quotes AS quote ON quote.id = job.quote_id
  WHERE visit.id = p_visit_id;
$$;

REVOKE ALL ON FUNCTION public.schedule_visit_backlog_fingerprint_v1(UUID)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.schedule_visit_backlog_fingerprint_v1(UUID)
  TO service_role;

CREATE OR REPLACE FUNCTION public.preview_schedule_visit_backlog_v1(
  p_visit_id UUID
)
RETURNS TABLE (
  visit_id UUID,
  job_id UUID,
  job_reference TEXT,
  sequence_number INTEGER,
  assignment_count INTEGER,
  fingerprint TEXT,
  already_queued BOOLEAN
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT
    visit.id,
    visit.job_id,
    job.job_reference::TEXT,
    visit.sequence_number,
    (
      (SELECT COUNT(*) FROM public.schedule_employee_assignments AS employee
        WHERE employee.visit_id = visit.id)
      +
      (SELECT COUNT(*) FROM public.schedule_plant_assignments AS plant
        WHERE plant.visit_id = visit.id)
    )::INTEGER,
    public.schedule_visit_backlog_fingerprint_v1(visit.id),
    backlog.visit_id IS NOT NULL
  FROM public.schedule_visits AS visit
  JOIN public.schedule_jobs AS job ON job.id = visit.job_id
  LEFT JOIN public.schedule_visit_backlog AS backlog ON backlog.visit_id = visit.id
  WHERE visit.id = p_visit_id;
$$;

REVOKE ALL ON FUNCTION public.preview_schedule_visit_backlog_v1(UUID)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.preview_schedule_visit_backlog_v1(UUID)
  TO service_role;

CREATE OR REPLACE FUNCTION public.lock_and_guard_schedule_assignment_backlog_v1()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_visit_id UUID;
  v_old_visit_id UUID;
  v_new_visit_id UUID;
BEGIN
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    v_old_visit_id := OLD.visit_id;
  END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    v_new_visit_id := NEW.visit_id;
  END IF;

  -- Lock both sides of a move in UUID order so enqueue, move, and delete
  -- serialize without deadlocks or stale assignment counts.
  FOR v_visit_id IN
    SELECT candidate
    FROM (
      VALUES (v_old_visit_id), (v_new_visit_id)
    ) AS visit_ids(candidate)
    WHERE candidate IS NOT NULL
    GROUP BY candidate
    ORDER BY candidate
  LOOP
    PERFORM 1
    FROM public.schedule_visits AS visit
    WHERE visit.id = v_visit_id
    FOR UPDATE;
  END LOOP;

  IF v_new_visit_id IS NOT NULL AND EXISTS (
    SELECT 1
    FROM public.schedule_visit_backlog AS backlog
    WHERE backlog.visit_id = v_new_visit_id
  ) THEN
    RAISE EXCEPTION 'VISIT_QUEUED'
      USING ERRCODE = 'P0001';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.lock_and_guard_schedule_assignment_backlog_v1()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS guard_employee_assignment_backlog
  ON public.schedule_employee_assignments;
CREATE TRIGGER guard_employee_assignment_backlog
  BEFORE INSERT OR UPDATE OR DELETE ON public.schedule_employee_assignments
  FOR EACH ROW EXECUTE FUNCTION public.lock_and_guard_schedule_assignment_backlog_v1();

DROP TRIGGER IF EXISTS guard_plant_assignment_backlog
  ON public.schedule_plant_assignments;
CREATE TRIGGER guard_plant_assignment_backlog
  BEFORE INSERT OR UPDATE OR DELETE ON public.schedule_plant_assignments
  FOR EACH ROW EXECUTE FUNCTION public.lock_and_guard_schedule_assignment_backlog_v1();

CREATE OR REPLACE FUNCTION public.guard_queued_schedule_visit_mutation_v1()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_visit_id UUID := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.schedule_visit_backlog AS backlog
    WHERE backlog.visit_id = v_visit_id
  ) THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' AND (
    NOT EXISTS (
      SELECT 1 FROM public.schedule_jobs AS job WHERE job.id = OLD.job_id
    )
  ) THEN
    -- Parent job deletion owns this cascade; the backlog marker cascades too.
    RETURN OLD;
  END IF;

  RAISE EXCEPTION 'VISIT_QUEUED'
    USING ERRCODE = 'P0001';
END;
$$;

REVOKE ALL ON FUNCTION public.guard_queued_schedule_visit_mutation_v1()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS guard_queued_schedule_visit_mutation
  ON public.schedule_visits;
CREATE TRIGGER guard_queued_schedule_visit_mutation
  BEFORE UPDATE OR DELETE ON public.schedule_visits
  FOR EACH ROW EXECUTE FUNCTION public.guard_queued_schedule_visit_mutation_v1();

-- Keep Quote synchronization backlog-aware so range contractions do not try
-- to mutate an immutable queued visit snapshot.
CREATE OR REPLACE FUNCTION public.sync_operational_quote_schedule_job()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  resolved_reference TEXT;
  resolved_title TEXT;
  resolved_end_date DATE;
  resolved_job_id UUID;
  is_schedulable BOOLEAN;
BEGIN
  is_schedulable :=
    NEW.is_latest_version = TRUE
    AND NEW.commercial_status = 'open'
    AND NEW.start_date IS NOT NULL;

  IF NOT is_schedulable THEN
    UPDATE public.schedule_jobs
    SET
      status = 'cancelled',
      updated_by = COALESCE(NEW.updated_by, NEW.created_by),
      updated_at = NOW()
    WHERE quote_id = NEW.id
      AND source_type = 'quote';
    RETURN NEW;
  END IF;

  resolved_reference := COALESCE(
    NULLIF(BTRIM(NEW.base_quote_reference), ''),
    NEW.quote_reference
  );
  resolved_title := COALESCE(
    NULLIF(BTRIM(NEW.subject_line), ''),
    NULLIF(BTRIM(NEW.project_description), ''),
    'Quoted work'
  );
  resolved_end_date :=
    NEW.start_date + GREATEST(COALESCE(NEW.estimated_duration_days, 1), 1) - 1;

  UPDATE public.schedule_jobs
  SET
    job_reference = resolved_reference,
    title = resolved_title,
    description = NEW.project_description,
    site_address = NEW.site_address,
    status = CASE WHEN NEW.status = 'in_progress' THEN 'in_progress' ELSE 'scheduled' END,
    start_date = NEW.start_date,
    end_date = resolved_end_date,
    estimated_duration_minutes = NEW.estimated_duration_minutes,
    customer_id = NEW.customer_id,
    customer_site_id = NEW.customer_site_id,
    updated_by = COALESCE(NEW.updated_by, NEW.created_by),
    updated_at = NOW()
  WHERE quote_id = NEW.id
    AND source_type = 'quote'
  RETURNING id INTO resolved_job_id;

  IF resolved_job_id IS NULL THEN
    INSERT INTO public.schedule_jobs (
      job_reference,
      title,
      description,
      site_address,
      status,
      source_type,
      start_date,
      end_date,
      estimated_duration_minutes,
      quote_id,
      customer_id,
      customer_site_id,
      created_by,
      updated_by
    )
    VALUES (
      resolved_reference,
      resolved_title,
      NEW.project_description,
      NEW.site_address,
      CASE WHEN NEW.status = 'in_progress' THEN 'in_progress' ELSE 'scheduled' END,
      'quote',
      NEW.start_date,
      resolved_end_date,
      NEW.estimated_duration_minutes,
      NEW.id,
      NEW.customer_id,
      NEW.customer_site_id,
      NEW.created_by,
      COALESCE(NEW.updated_by, NEW.created_by)
    )
    ON CONFLICT (job_reference) DO UPDATE
    SET
      title = EXCLUDED.title,
      description = EXCLUDED.description,
      site_address = EXCLUDED.site_address,
      status = EXCLUDED.status,
      source_type = 'quote',
      start_date = EXCLUDED.start_date,
      end_date = EXCLUDED.end_date,
      estimated_duration_minutes = EXCLUDED.estimated_duration_minutes,
      quote_id = EXCLUDED.quote_id,
      customer_id = EXCLUDED.customer_id,
      customer_site_id = EXCLUDED.customer_site_id,
      updated_by = EXCLUDED.updated_by,
      updated_at = NOW()
    WHERE public.schedule_jobs.source_type = 'quote'
    RETURNING id INTO resolved_job_id;
  END IF;

  IF resolved_job_id IS NULL THEN
    RAISE EXCEPTION
      'Scheduling job reference % is already owned by a non-Quote job.',
      resolved_reference;
  END IF;

  UPDATE public.schedule_visits AS visit
  SET
    status = 'cancelled',
    updated_by = COALESCE(NEW.updated_by, NEW.created_by),
    updated_at = NOW()
  WHERE visit.job_id = resolved_job_id
    AND visit.status <> 'cancelled'
    AND (
      (visit.starts_at AT TIME ZONE 'Europe/London')::DATE < NEW.start_date
      OR (visit.starts_at AT TIME ZONE 'Europe/London')::DATE > resolved_end_date
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.schedule_visit_backlog AS backlog
      WHERE backlog.visit_id = visit.id
    );

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.sync_operational_quote_schedule_job()
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.enqueue_schedule_visit_v1(
  p_request_id UUID,
  p_visit_id UUID,
  p_expected_fingerprint TEXT,
  p_actor_user_id UUID
)
RETURNS TABLE (
  visit_id UUID,
  job_id UUID,
  assignment_count INTEGER,
  queued_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_visit public.schedule_visits%ROWTYPE;
  v_job_seed public.schedule_jobs%ROWTYPE;
  v_job public.schedule_jobs%ROWTYPE;
  v_quote public.quotes%ROWTYPE;
  v_existing public.schedule_visit_transition_requests%ROWTYPE;
  v_fingerprint TEXT;
  v_assignment_count INTEGER;
  v_queued_at TIMESTAMPTZ := NOW();
  v_input_hash TEXT;
  v_result JSONB;
BEGIN
  IF p_request_id IS NULL OR p_visit_id IS NULL OR p_actor_user_id IS NULL THEN
    RAISE EXCEPTION 'A request, visit, and actor are required.';
  END IF;
  IF NULLIF(BTRIM(COALESCE(p_expected_fingerprint, '')), '') IS NULL THEN
    RAISE EXCEPTION 'A visit fingerprint is required.';
  END IF;

  v_input_hash := md5(
    p_visit_id::TEXT || '|enqueue|' || p_expected_fingerprint
  );
  PERFORM pg_advisory_xact_lock(hashtextextended(p_request_id::TEXT, 0));

  SELECT *
  INTO v_existing
  FROM public.schedule_visit_transition_requests AS transition
  WHERE transition.request_id = p_request_id;

  IF FOUND THEN
    IF v_existing.action <> 'enqueue'
       OR v_existing.visit_id <> p_visit_id
       OR v_existing.input_hash <> v_input_hash THEN
      RAISE EXCEPTION 'REQUEST_ID_REUSED'
        USING ERRCODE = 'P0001';
    END IF;
    RETURN QUERY
    SELECT
      (v_existing.result->>'visit_id')::UUID,
      (v_existing.result->>'job_id')::UUID,
      (v_existing.result->>'assignment_count')::INTEGER,
      (v_existing.result->>'queued_at')::TIMESTAMPTZ;
    RETURN;
  END IF;

  SELECT *
  INTO v_visit
  FROM public.schedule_visits AS visit
  WHERE visit.id = p_visit_id;

  IF v_visit.id IS NULL THEN
    RAISE EXCEPTION 'VISIT_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_job_seed
  FROM public.schedule_jobs AS job
  WHERE job.id = v_visit.job_id;
  IF v_job_seed.id IS NULL THEN
    RAISE EXCEPTION 'JOB_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;

  IF v_job_seed.source_type = 'quote' THEN
    SELECT *
    INTO v_quote
    FROM public.quotes AS quote
    WHERE quote.id = v_job_seed.quote_id
    FOR UPDATE;
    IF v_quote.id IS NULL
       OR v_quote.is_latest_version IS DISTINCT FROM TRUE
       OR v_quote.commercial_status IS DISTINCT FROM 'open'
       OR v_quote.start_date IS NULL THEN
      RAISE EXCEPTION 'QUOTE_NOT_SCHEDULABLE'
        USING ERRCODE = 'P0001';
    END IF;

    SELECT *
    INTO v_job
    FROM public.schedule_jobs AS job
    WHERE job.id = v_visit.job_id
    FOR UPDATE;
    IF v_job.source_type <> 'quote'
       OR v_job.quote_id IS DISTINCT FROM v_quote.id THEN
      RAISE EXCEPTION 'JOB_CHANGED'
        USING ERRCODE = 'P0001';
    END IF;
  ELSE
    SELECT *
    INTO v_job
    FROM public.schedule_jobs AS job
    WHERE job.id = v_visit.job_id
    FOR UPDATE;
    IF v_job.source_type = 'quote'
       OR v_job.status IN ('completed', 'cancelled') THEN
      RAISE EXCEPTION 'JOB_NOT_SCHEDULABLE'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;

  -- Assignment mutation RPCs lock their row before visit rows. Match that
  -- order here to avoid row-lock/visit-lock inversion during enqueue.
  PERFORM employee.id
  FROM public.schedule_employee_assignments AS employee
  WHERE employee.visit_id = p_visit_id
  ORDER BY employee.id
  FOR UPDATE;
  PERFORM plant.id
  FROM public.schedule_plant_assignments AS plant
  WHERE plant.visit_id = p_visit_id
  ORDER BY plant.id
  FOR UPDATE;

  SELECT *
  INTO v_visit
  FROM public.schedule_visits AS visit
  WHERE visit.id = p_visit_id
  FOR UPDATE;
  IF v_visit.id IS NULL OR v_visit.job_id <> v_job.id THEN
    RAISE EXCEPTION 'VISIT_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;
  IF v_visit.status IN ('completed', 'cancelled') THEN
    RAISE EXCEPTION 'VISIT_NOT_QUEUEABLE'
      USING ERRCODE = 'P0001';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM public.schedule_visit_backlog AS backlog
    WHERE backlog.visit_id = p_visit_id
  ) THEN
    RAISE EXCEPTION 'VISIT_ALREADY_QUEUED'
      USING ERRCODE = 'P0001';
  END IF;

  v_fingerprint := public.schedule_visit_backlog_fingerprint_v1(p_visit_id);
  IF v_fingerprint IS DISTINCT FROM p_expected_fingerprint THEN
    RAISE EXCEPTION 'STALE_VISIT_PREVIEW'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT (
    (SELECT COUNT(*) FROM public.schedule_employee_assignments AS employee
      WHERE employee.visit_id = p_visit_id)
    +
    (SELECT COUNT(*) FROM public.schedule_plant_assignments AS plant
      WHERE plant.visit_id = p_visit_id)
  )::INTEGER
  INTO v_assignment_count;

  INSERT INTO public.schedule_visit_backlog (
    visit_id,
    original_starts_at,
    original_ends_at,
    queued_by,
    queued_at
  )
  VALUES (
    v_visit.id,
    v_visit.starts_at,
    v_visit.ends_at,
    p_actor_user_id,
    v_queued_at
  );

  DELETE FROM public.schedule_employee_assignments AS employee
  WHERE employee.visit_id = p_visit_id;
  DELETE FROM public.schedule_plant_assignments AS plant
  WHERE plant.visit_id = p_visit_id;

  INSERT INTO public.schedule_visit_transition_events (
    visit_id,
    job_id,
    action,
    actor_user_id,
    assignment_count,
    from_starts_at,
    from_ends_at
  )
  VALUES (
    v_visit.id,
    v_visit.job_id,
    'enqueue',
    p_actor_user_id,
    v_assignment_count,
    v_visit.starts_at,
    v_visit.ends_at
  );

  v_result := jsonb_build_object(
    'visit_id', v_visit.id,
    'job_id', v_visit.job_id,
    'assignment_count', v_assignment_count,
    'queued_at', v_queued_at
  );

  INSERT INTO public.schedule_visit_transition_requests (
    request_id,
    action,
    visit_id,
    actor_user_id,
    input_hash,
    result
  )
  VALUES (
    p_request_id,
    'enqueue',
    v_visit.id,
    p_actor_user_id,
    v_input_hash,
    v_result
  );

  RETURN QUERY
  SELECT v_visit.id, v_visit.job_id, v_assignment_count, v_queued_at;
END;
$$;

REVOKE ALL ON FUNCTION public.enqueue_schedule_visit_v1(
  UUID, UUID, TEXT, UUID
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_schedule_visit_v1(
  UUID, UUID, TEXT, UUID
) TO service_role;

CREATE OR REPLACE FUNCTION public.schedule_queued_visit_v1(
  p_request_id UUID,
  p_visit_id UUID,
  p_starts_at TIMESTAMPTZ,
  p_actor_user_id UUID
)
RETURNS TABLE (
  visit_id UUID,
  job_id UUID,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  job_start_date DATE,
  job_end_date DATE
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_visit public.schedule_visits%ROWTYPE;
  v_backlog public.schedule_visit_backlog%ROWTYPE;
  v_job_seed public.schedule_jobs%ROWTYPE;
  v_job public.schedule_jobs%ROWTYPE;
  v_quote public.quotes%ROWTYPE;
  v_existing public.schedule_visit_transition_requests%ROWTYPE;
  v_target_date DATE;
  v_new_start DATE;
  v_new_end DATE;
  v_resolved_ends TIMESTAMPTZ;
  v_input_hash TEXT;
  v_result JSONB;
BEGIN
  IF p_request_id IS NULL OR p_visit_id IS NULL OR p_actor_user_id IS NULL THEN
    RAISE EXCEPTION 'A request, visit, and actor are required.';
  END IF;
  IF p_starts_at IS NULL THEN
    RAISE EXCEPTION 'INVALID_VISIT_WINDOW'
      USING ERRCODE = 'P0001';
  END IF;

  v_input_hash := md5(
    concat_ws(
      '|',
      p_visit_id::TEXT,
      'schedule',
      p_starts_at::TEXT
    )
  );
  PERFORM pg_advisory_xact_lock(hashtextextended(p_request_id::TEXT, 0));

  SELECT *
  INTO v_existing
  FROM public.schedule_visit_transition_requests AS transition
  WHERE transition.request_id = p_request_id;

  IF FOUND THEN
    IF v_existing.action <> 'schedule'
       OR v_existing.visit_id <> p_visit_id
       OR v_existing.input_hash <> v_input_hash THEN
      RAISE EXCEPTION 'REQUEST_ID_REUSED'
        USING ERRCODE = 'P0001';
    END IF;
    RETURN QUERY
    SELECT
      (v_existing.result->>'visit_id')::UUID,
      (v_existing.result->>'job_id')::UUID,
      (v_existing.result->>'starts_at')::TIMESTAMPTZ,
      (v_existing.result->>'ends_at')::TIMESTAMPTZ,
      (v_existing.result->>'job_start_date')::DATE,
      (v_existing.result->>'job_end_date')::DATE;
    RETURN;
  END IF;

  SELECT *
  INTO v_visit
  FROM public.schedule_visits AS visit
  WHERE visit.id = p_visit_id;

  IF v_visit.id IS NULL THEN
    RAISE EXCEPTION 'VISIT_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_job_seed
  FROM public.schedule_jobs AS job
  WHERE job.id = v_visit.job_id;

  IF v_job_seed.id IS NULL THEN
    RAISE EXCEPTION 'JOB_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;

  v_target_date := (p_starts_at AT TIME ZONE 'Europe/London')::DATE;

  IF v_job_seed.source_type = 'quote' THEN
    -- Match the authoritative Quote -> job -> visit lock order used by sync.
    SELECT *
    INTO v_quote
    FROM public.quotes AS quote
    WHERE quote.id = v_job_seed.quote_id
    FOR UPDATE;

    IF v_quote.id IS NULL
       OR v_quote.is_latest_version IS DISTINCT FROM TRUE
       OR v_quote.commercial_status IS DISTINCT FROM 'open'
       OR v_quote.start_date IS NULL THEN
      RAISE EXCEPTION 'QUOTE_NOT_SCHEDULABLE'
        USING ERRCODE = 'P0001';
    END IF;

    SELECT *
    INTO v_job
    FROM public.schedule_jobs AS job
    WHERE job.id = v_visit.job_id
    FOR UPDATE;
    IF v_job.source_type <> 'quote'
       OR v_job.quote_id IS DISTINCT FROM v_quote.id THEN
      RAISE EXCEPTION 'JOB_CHANGED'
        USING ERRCODE = 'P0001';
    END IF;
  ELSE
    SELECT *
    INTO v_job
    FROM public.schedule_jobs AS job
    WHERE job.id = v_visit.job_id
    FOR UPDATE;
    IF v_job.source_type = 'quote'
       OR v_job.status IN ('completed', 'cancelled') THEN
      RAISE EXCEPTION 'JOB_NOT_SCHEDULABLE'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;

  SELECT *
  INTO v_visit
  FROM public.schedule_visits AS visit
  WHERE visit.id = p_visit_id
  FOR UPDATE;
  IF v_visit.id IS NULL OR v_visit.job_id <> v_job.id THEN
    RAISE EXCEPTION 'VISIT_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;
  IF v_visit.status IN ('completed', 'cancelled') THEN
    RAISE EXCEPTION 'VISIT_NOT_QUEUEABLE'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_backlog
  FROM public.schedule_visit_backlog AS backlog
  WHERE backlog.visit_id = p_visit_id
  FOR UPDATE;
  IF v_backlog.visit_id IS NULL THEN
    RAISE EXCEPTION 'VISIT_NOT_QUEUED'
      USING ERRCODE = 'P0001';
  END IF;
  v_resolved_ends := p_starts_at
    + (v_backlog.original_ends_at - v_backlog.original_starts_at);
  IF (p_starts_at AT TIME ZONE 'Europe/London')::DATE
     <> (v_resolved_ends AT TIME ZONE 'Europe/London')::DATE THEN
    RAISE EXCEPTION 'VISIT_MUST_FIT_ONE_DAY'
      USING ERRCODE = 'P0001';
  END IF;

  IF v_job.source_type = 'quote' THEN
    v_new_start := LEAST(v_quote.start_date, v_target_date);
    v_new_end := GREATEST(
      v_quote.start_date
        + GREATEST(COALESCE(v_quote.estimated_duration_days, 1), 1) - 1,
      v_target_date
    );

    UPDATE public.quotes
    SET
      start_date = v_new_start,
      estimated_duration_days = (v_new_end - v_new_start) + 1,
      updated_by = p_actor_user_id,
      updated_at = NOW()
    WHERE quotes.id = v_quote.id;

    SELECT *
    INTO v_job
    FROM public.schedule_jobs AS job
    WHERE job.id = v_visit.job_id;
  ELSE
    v_new_start := LEAST(v_job.start_date, v_target_date);
    v_new_end := GREATEST(v_job.end_date, v_target_date);

    UPDATE public.schedule_jobs
    SET
      start_date = v_new_start,
      end_date = v_new_end,
      updated_by = p_actor_user_id,
      updated_at = NOW()
    WHERE schedule_jobs.id = v_job.id
    RETURNING * INTO v_job;
  END IF;

  -- Remove the marker inside this transaction before updating the immutable
  -- visit snapshot. Other transactions cannot observe the deletion until commit.
  DELETE FROM public.schedule_visit_backlog AS backlog
  WHERE backlog.visit_id = v_visit.id;

  UPDATE public.schedule_visits
  SET
    starts_at = p_starts_at,
    ends_at = v_resolved_ends,
    updated_by = p_actor_user_id,
    updated_at = NOW()
  WHERE schedule_visits.id = v_visit.id;

  INSERT INTO public.schedule_visit_transition_events (
    visit_id,
    job_id,
    action,
    actor_user_id,
    from_starts_at,
    from_ends_at,
    to_starts_at,
    to_ends_at
  )
  VALUES (
    v_visit.id,
    v_visit.job_id,
    'schedule',
    p_actor_user_id,
    v_visit.starts_at,
    v_visit.ends_at,
    p_starts_at,
    v_resolved_ends
  );

  v_result := jsonb_build_object(
    'visit_id', v_visit.id,
    'job_id', v_visit.job_id,
    'starts_at', p_starts_at,
    'ends_at', v_resolved_ends,
    'job_start_date', v_job.start_date,
    'job_end_date', v_job.end_date
  );

  INSERT INTO public.schedule_visit_transition_requests (
    request_id,
    action,
    visit_id,
    actor_user_id,
    input_hash,
    result
  )
  VALUES (
    p_request_id,
    'schedule',
    v_visit.id,
    p_actor_user_id,
    v_input_hash,
    v_result
  );

  RETURN QUERY
  SELECT
    v_visit.id,
    v_visit.job_id,
    p_starts_at,
    v_resolved_ends,
    v_job.start_date,
    v_job.end_date;
END;
$$;

REVOKE ALL ON FUNCTION public.schedule_queued_visit_v1(
  UUID, UUID, TIMESTAMPTZ, UUID
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.schedule_queued_visit_v1(
  UUID, UUID, TIMESTAMPTZ, UUID
) TO service_role;

COMMENT ON TABLE public.schedule_visit_backlog IS
  'Marks an existing scheduling visit as queued in Resources > Jobs without changing its identity.';
COMMENT ON FUNCTION public.enqueue_schedule_visit_v1(UUID, UUID, TEXT, UUID) IS
  'Atomically queues one planned visit and removes only that visit resource assignments.';
COMMENT ON FUNCTION public.schedule_queued_visit_v1(
  UUID, UUID, TIMESTAMPTZ, UUID
) IS
  'Atomically returns a queued visit to the board while expanding, never contracting, its planning range.';

COMMIT;
